import { ResearchField, ResearchTask } from './types';
import { Atom, Microscope, Binary, Sigma, Users, Globe, FileSearch, BarChart, TestTube, PenTool, Sparkles, FileText, Network, Feather, PieChart, BrainCircuit, Code } from 'lucide-react';

export const THEME_STYLES: Record<string, any> = {
  violet: {
    iconBg: "bg-violet-500/20",
    iconText: "text-violet-400",
    subtitle: "text-violet-300",
    border: "border-violet-500/30",
    shadow: "shadow-violet-900/10",
    headerBg: "bg-violet-900/10",
    headerBorder: "border-violet-500/20",
    chipBg: "bg-violet-900/30",
    chipText: "text-violet-200",
    inputGradient: "from-violet-600",
    sendButton: "bg-violet-600",
    sendButtonHover: "hover:bg-violet-500",
    titleShadow: "shadow-violet-500/50",
    sendShadow: "shadow-violet-900/20"
  },
  emerald: {
    iconBg: "bg-emerald-500/20",
    iconText: "text-emerald-400",
    subtitle: "text-emerald-300",
    border: "border-emerald-500/30",
    shadow: "shadow-emerald-900/10",
    headerBg: "bg-emerald-900/10",
    headerBorder: "border-emerald-500/20",
    chipBg: "bg-emerald-900/30",
    chipText: "text-emerald-200",
    inputGradient: "from-emerald-600",
    sendButton: "bg-emerald-600",
    sendButtonHover: "hover:bg-emerald-500",
    titleShadow: "shadow-emerald-500/50",
    sendShadow: "shadow-emerald-900/20"
  },
  cyan: {
    iconBg: "bg-cyan-500/20",
    iconText: "text-cyan-400",
    subtitle: "text-cyan-300",
    border: "border-cyan-500/30",
    shadow: "shadow-cyan-900/10",
    headerBg: "bg-cyan-900/10",
    headerBorder: "border-cyan-500/20",
    chipBg: "bg-cyan-900/30",
    chipText: "text-cyan-200",
    inputGradient: "from-cyan-600",
    sendButton: "bg-cyan-600",
    sendButtonHover: "hover:bg-cyan-500",
    titleShadow: "shadow-cyan-500/50",
    sendShadow: "shadow-cyan-900/20"
  },
  amber: {
    iconBg: "bg-amber-500/20",
    iconText: "text-amber-400",
    subtitle: "text-amber-300",
    border: "border-amber-500/30",
    shadow: "shadow-amber-900/10",
    headerBg: "bg-amber-900/10",
    headerBorder: "border-amber-500/20",
    chipBg: "bg-amber-900/30",
    chipText: "text-amber-200",
    inputGradient: "from-amber-600",
    sendButton: "bg-amber-600",
    sendButtonHover: "hover:bg-amber-500",
    titleShadow: "shadow-amber-500/50",
    sendShadow: "shadow-amber-900/20"
  },
  rose: {
    iconBg: "bg-rose-500/20",
    iconText: "text-rose-400",
    subtitle: "text-rose-300",
    border: "border-rose-500/30",
    shadow: "shadow-rose-900/10",
    headerBg: "bg-rose-900/10",
    headerBorder: "border-rose-500/20",
    chipBg: "bg-rose-900/30",
    chipText: "text-rose-200",
    inputGradient: "from-rose-600",
    sendButton: "bg-rose-600",
    sendButtonHover: "hover:bg-rose-500",
    titleShadow: "shadow-rose-500/50",
    sendShadow: "shadow-rose-900/20"
  },
  blue: {
    iconBg: "bg-blue-500/20",
    iconText: "text-blue-400",
    subtitle: "text-blue-300",
    border: "border-blue-500/30",
    shadow: "shadow-blue-900/10",
    headerBg: "bg-blue-900/10",
    headerBorder: "border-blue-500/20",
    chipBg: "bg-blue-900/30",
    chipText: "text-blue-200",
    inputGradient: "from-blue-600",
    sendButton: "bg-blue-600",
    sendButtonHover: "hover:bg-blue-500",
    titleShadow: "shadow-blue-500/50",
    sendShadow: "shadow-blue-900/20"
  }
};

export const FIELD_CONFIG = {
  [ResearchField.PHYSICS]: {
    color: 'violet',
    icon: Atom,
    description: "Quantum mechanics, Astrophysics, Relativity",
    themeClass: "from-violet-500 to-purple-600",
    borderClass: "border-violet-500/50",
    hoverBorderClass: "hover:border-violet-500/50",
    bgClass: "bg-violet-900/20",
    textAccent: "text-violet-400",
    groupHoverTextAccent: "group-hover:text-violet-400",
    checkboxBg: "bg-violet-500",
    launchButtonStyle: "bg-violet-600 hover:bg-violet-500",
    tasks: [
      { id: ResearchTask.DEEP_SEARCH, title: "Literature Review", desc: "ArXiv & APS synthesis", icon: FileSearch },
      { id: ResearchTask.DATA_ANALYSIS, title: "Simulation Data", desc: "Analyze experimental datasets", icon: BarChart },
      { id: ResearchTask.IDEA_GENERATION, title: "Theory Derivation", desc: "Brainstorm mathematical models", icon: Sigma },
    ]
  },
  [ResearchField.BIOLOGY]: {
    color: 'emerald',
    icon: Microscope,
    description: "Genomics, Proteomics, Bioinformatics",
    themeClass: "from-emerald-400 to-green-600",
    borderClass: "border-emerald-500/50",
    hoverBorderClass: "hover:border-emerald-500/50",
    bgClass: "bg-emerald-900/20",
    textAccent: "text-emerald-400",
    groupHoverTextAccent: "group-hover:text-emerald-400",
    checkboxBg: "bg-emerald-500",
    launchButtonStyle: "bg-emerald-600 hover:bg-emerald-500",
    tasks: [
      { id: ResearchTask.DEEP_SEARCH, title: "PubMed Search", desc: "Find recent protocols", icon: FileSearch },
      { id: ResearchTask.DATA_ANALYSIS, title: "Bioinformatics", desc: "Sequence & protein analysis", icon: TestTube },
      { id: ResearchTask.PAPER_EDITING, title: "Lab Report Polish", desc: "Format for Nature/Cell", icon: PenTool },
    ]
  },
  [ResearchField.CS]: {
    color: 'cyan',
    icon: Binary,
    description: "AI/ML, Algorithms, Systems",
    themeClass: "from-cyan-400 to-blue-600",
    borderClass: "border-cyan-500/50",
    hoverBorderClass: "hover:border-cyan-500/50",
    bgClass: "bg-cyan-900/20",
    textAccent: "text-cyan-400",
    groupHoverTextAccent: "group-hover:text-cyan-400",
    checkboxBg: "bg-cyan-500",
    launchButtonStyle: "bg-cyan-600 hover:bg-cyan-500",
    tasks: [
      { id: ResearchTask.DEEP_SEARCH, title: "Tech Stack Review", desc: "Compare frameworks & tools", icon: Network },
      { id: ResearchTask.DATA_ANALYSIS, title: "Code Analysis", desc: "Debug & Optimize algorithms", icon: Code },
      { id: ResearchTask.IDEA_GENERATION, title: "System Design", desc: "Architect scalable solutions", icon: BrainCircuit },
    ]
  },
  [ResearchField.MATH]: {
    color: 'amber',
    icon: Sigma,
    description: "Topology, Number Theory, Analysis",
    themeClass: "from-amber-400 to-orange-600",
    borderClass: "border-amber-500/50",
    hoverBorderClass: "hover:border-amber-500/50",
    bgClass: "bg-amber-900/20",
    textAccent: "text-amber-400",
    groupHoverTextAccent: "group-hover:text-amber-400",
    checkboxBg: "bg-amber-500",
    launchButtonStyle: "bg-amber-600 hover:bg-amber-500",
    tasks: [
      { id: ResearchTask.IDEA_GENERATION, title: "Proof Assistant", desc: "Verify logical steps", icon: Sparkles },
      { id: ResearchTask.PAPER_READING, title: "Paper Deconstruction", desc: "Simplify complex theorems", icon: FileText },
      { id: ResearchTask.PAPER_EDITING, title: "LaTeX Formatting", desc: "Fix equation syntax", icon: PenTool },
    ]
  },
  [ResearchField.SOCIAL]: {
    color: 'rose',
    icon: Users,
    description: "Psychology, Sociology, Economics",
    themeClass: "from-rose-400 to-pink-600",
    borderClass: "border-rose-500/50",
    hoverBorderClass: "hover:border-rose-500/50",
    bgClass: "bg-rose-900/20",
    textAccent: "text-rose-400",
    groupHoverTextAccent: "group-hover:text-rose-400",
    checkboxBg: "bg-rose-500",
    launchButtonStyle: "bg-rose-600 hover:bg-rose-500",
    tasks: [
      { id: ResearchTask.DEEP_SEARCH, title: "Lit Synthesis", desc: "Qualitative meta-analysis", icon: Feather },
      { id: ResearchTask.DATA_ANALYSIS, title: "SPSS/R Stats", desc: "Survey data interpretation", icon: PieChart },
      { id: ResearchTask.IDEA_GENERATION, title: "Study Design", desc: "Methodology planning", icon: Users },
    ]
  },
  [ResearchField.GENERAL]: {
    color: 'blue',
    icon: Globe,
    description: "Interdisciplinary Studies",
    themeClass: "from-blue-400 to-indigo-600",
    borderClass: "border-blue-500/50",
    hoverBorderClass: "hover:border-blue-500/50",
    bgClass: "bg-blue-900/20",
    textAccent: "text-blue-400",
    groupHoverTextAccent: "group-hover:text-blue-400",
    checkboxBg: "bg-blue-500",
    launchButtonStyle: "bg-blue-600 hover:bg-blue-500",
    tasks: [
      { id: ResearchTask.DEEP_SEARCH, title: "Deep Research", desc: "Comprehensive review", icon: FileSearch },
      { id: ResearchTask.PAPER_READING, title: "Paper Reader", desc: "Summarize PDF/Text", icon: FileText },
      { id: ResearchTask.PAPER_EDITING, title: "Academic Editing", desc: "Polish writing", icon: PenTool },
      { id: ResearchTask.DATA_ANALYSIS, title: "Data Analysis", desc: "Statistical consulting", icon: BarChart },
      { id: ResearchTask.IDEA_GENERATION, title: "Hypothesis Gen", desc: "Brainstorming ideas", icon: Sparkles },
    ]
  },
};
